### ISSUE TITLE
这个如何使用

### ISSUE THREAD

**Issue by nyrf** [work-design/rails_wechat#4]
你好，请问这个如何使用？我看没有migrate文件？

**Comment by qinmingyuan** [comment]
抱歉，文档极度缺乏。
这个需要配合：https://github.com/work-design/rails_com  这个通用 engine 使用；

bin/rails  g rails_com:migrations  会自动根据 attribute 及 belongs_to 生成 migration 文件。
如果诚心想用，可以加我微信 mingyuan0715

**Comment by qinmingyuan** [comment]
抱歉，文档极度缺乏。
这个需要配合：https://github.com/work-design/rails_com  这个通用 engine 使用；

bin/rails  g rails_com:migrations  会自动根据 attribute 及 belongs_to 生成 migration 文件。
如果诚心想用，可以加我微信 mingyuan0715

**Comment by qinmingyuan** [comment]
https://daotestimg.dao42.com/ipic/Rails%20Engine%E7%BB%84%E4%BB%B6%E5%8C%96%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5_%E8%A6%83%E6%98%8E%E5%9C%86.pdf
